version: '3'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 125M
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/data-mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data-mosquitto/data:/mosquitto/data
      - ./mosquitto/data-mosquitto/log:/mosquitto/log
      - ./mosquitto/data-mosquitto/passwords:/mosquitto/passwords
